version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pastebin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/java/com/pastebin/util/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  app:
    build:
      context: .
      args:
        - SPRING_ACTIVE_PROFILE=docker
    image: lxndrreset/spring-pastebin:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pastebin
      - SPRING_ACTIVE_PROFILE=docker
    depends_on:
      - db
volumes:
  db_data: {}